config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products do
     resources :reviews, except: [:index, :new, :show]
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :reviews, :dependent => :destroy

  validates :name, :description, :price, presence: true
  validates :price, numericality: { only_integer:  true }


end

app/models/review.rb
class Review < ApplicationRecord
  validates :comment, :product_id, presence: true

  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash.notice = 'Saved succesfully'
      redirect_to @product
    else
      render :new
    end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
    @review = Review.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    #
    if @product.update(product_params)
      flash.notice = 'Saved succesfully'
      redirect_to @product
    else
      render :edit
    end

    # render plain: params[:product].inspect
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash.notice = "Delete successful"
    redirect_to products_path
  end
end

private
def product_params
  params.require(:product).permit(:name, :description, :price)
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(
    comment: params[:review][:comment],
    product_id: params[:product_id]
    )

    if @review.save
      # flash.notice = 'Saved succesfully'
      redirect_to product_path(params[:product_id])
    else
      @product = Product.find(params[:product_id])
      @reviews = @product.reviews
      render "/products/show"
      # render product_path(params[:product_id])
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = @product.reviews.find(params[:id])
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])

    @review.comment = params[:review][:comment]

    if @review.save
      redirect_to product_path(params[:product_id])
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.delete
    redirect_to product_path(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def price_in_dollars(price)
  price_in_dollars = price.to_f / 100
  sprintf("$%.2f", price_in_dollars)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to "Add a new product", new_product_path %> |
      <%= link_to "Back to products", products_path %>
    </nav>

    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>


    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for product do |f| %>
<p>
<%= f.label :name %>
<%= f.text_field :name %>
</p>
<p>
  <%= f.label :price %>
  <%= f.text_field :price %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<% if product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(product.errors.count, "error") %> prohibited this article from being saved:</h2>

    <ul>
    <% product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit <%= @product.name.capitalize %></h1>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1>Products</h1>
<ul>
  <% @products.each do |product| %>
  <li><%= link_to "#{product.name}", product_path(product.id) %> | <%= price_in_dollars(product.price) %> | <%= product.description %></li>
  <% end %>
</ul>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h1><%= "#{@product.name.capitalize}" %></h1>
  <%= @product.name %> | <%= price_in_dollars(@product.price)%> | <%= @product.description %></li>
<br>
<%= link_to "Edit", edit_product_path(@product) %> | <%= link_to("Delete", product_path(@product), method: :delete, data: {confirm: "Are you sure you want to delete this product?"})  %>
<h2>Reviews</h2>
<ul>
  <% @reviews.each do |review| %>
  <li><%= review.comment %> | <%= review.created_at %> |
  <%= link_to "Edit", edit_product_review_path(review.product, review) %> |
  <%= link_to "Delete", product_review_path(review.product, review), method: :delete, data: {confirm: ("Are you sure you want to delete this comment?")} %></li>
  <% end %>
</ul>

<%= render 'reviews/form', review: @review, product: @product %>

app/views/reviews/_form.html.erb
<% console %>
<%= form_for ([product, review]) do |f| %>
  <% if review.errors.any? %>
    <div id = "error_explanation">
      <p><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved: </p>
      <ul>
        <% review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end  %>

  <p>
    <%= f.label :comment, "New Review" %><br />
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit comment</h1>

<%= render 'form', review: @review, product: @product %>